import Providers from "@/providers/Providers";
import "../styles/globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="flex-col hidden md:flex">
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
